In [1]:
import scipy.signal
import numpy
import sys
sys.path.append('..')

In [2]:
import eaglecore.differential
import eaglecore.utils
# import lasp.filters.linear

In [3]:
arr = numpy.reshape(numpy.arange(0, 16), (4, 4))
arr_fft = numpy.fft.fftn(arr) # img in frequency domain
print(arr)
print(arr_fft)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[120. +0.j  -8. +8.j  -8. +0.j  -8. -8.j]
 [-32.+32.j   0. +0.j   0. +0.j   0. +0.j]
 [-32. +0.j   0. +0.j   0. +0.j   0. +0.j]
 [-32.-32.j   0. +0.j   0. +0.j   0. +0.j]]


## Circular boundary condition

### $\nabla_{x}$

In [4]:
kernel2d_id = numpy.pad(numpy.array([[1]]), pad_width=1)
dx_oper = eaglecore.differential.difference_finite_circular(
    array = kernel2d_id,
    axis = 1
)

## With convolution (ie spatial domain)
arr_dx_v1 = scipy.signal.convolve2d(
    arr, 
    dx_oper, 
    mode='same',
    boundary='circular'
)

## BCCB tricks
dx_oper_diag = eaglecore.utils.fourier_diagonalization(dx_oper, arr.shape)
arr_fft_dx_v2 = dx_oper_diag * arr_fft
arr_dx_v2 = numpy.real(numpy.fft.ifft2(arr_fft_dx_v2))


## With numpy
arr_dx_v3 = eaglecore.differential.difference_finite_circular(
    array = arr,
    axis = 1
)

print('Kernel identity :\n', kernel2d_id)
print('dx_oper :\n', dx_oper)

print('conv2d :\n', arr_dx_v1)
print('BCCB :\n', arr_dx_v2)
print('Direct :\n', arr_dx_v3)

# print(eaglecore.differential.dx(arr))


Kernel identity :
 [[0 0 0]
 [0 1 0]
 [0 0 0]]
dx_oper :
 [[ 0  0  0]
 [ 0  1 -1]
 [ 0  0  0]]
conv2d :
 [[-3  1  1  1]
 [-3  1  1  1]
 [-3  1  1  1]
 [-3  1  1  1]]
BCCB :
 [[-3.  1.  1.  1.]
 [-3.  1.  1.  1.]
 [-3.  1.  1.  1.]
 [-3.  1.  1.  1.]]
Direct :
 [[-3  1  1  1]
 [-3  1  1  1]
 [-3  1  1  1]
 [-3  1  1  1]]


### $\nabla_{y}$

In [5]:
kernel2d_id = numpy.pad(numpy.array([[1]]), pad_width=1)
dy_oper = eaglecore.differential.difference_finite_circular(
    array = kernel2d_id,
    axis = 0
)

## With convolution (ie spatial domain)
arr_dy_v1 = scipy.signal.convolve2d(
    arr, 
    dy_oper, 
    mode='same',
    boundary='circular'
)

## BCCB tricks
dy_oper_diag = eaglecore.utils.fourier_diagonalization(dy_oper, arr.shape)
arr_fft_dy_v2 = dy_oper_diag * arr_fft
arr_dy_v2 = numpy.real(numpy.fft.ifft2(arr_fft_dy_v2))


## With numpy
arr_dy_v3 = eaglecore.differential.difference_finite_circular(
    array = arr,
    axis = 0
)

print('Kernel identity :\n', kernel2d_id)
print('dy_oper :\n', dy_oper)

print('conv2d :\n', arr_dy_v1)
print('BCCB :\n', arr_dy_v2)
print('Direct :\n', arr_dy_v3)

# print(eaglecore.differential.dy(arr))

Kernel identity :
 [[0 0 0]
 [0 1 0]
 [0 0 0]]
dy_oper :
 [[ 0  0  0]
 [ 0  1  0]
 [ 0 -1  0]]
conv2d :
 [[-12 -12 -12 -12]
 [  4   4   4   4]
 [  4   4   4   4]
 [  4   4   4   4]]
BCCB :
 [[-12. -12. -12. -12.]
 [  4.   4.   4.   4.]
 [  4.   4.   4.   4.]
 [  4.   4.   4.   4.]]
Direct :
 [[-12 -12 -12 -12]
 [  4   4   4   4]
 [  4   4   4   4]
 [  4   4   4   4]]


### $\nabla_{x}^{T}$

In [6]:
kernel2d_id = numpy.pad(numpy.array([[1]]), pad_width=1)

dxT_oper = eaglecore.differential.transposed_difference_finite_circular(
    array = kernel2d_id,
    axis = 1
)

## With convolution (ie spatial domain)
arr_dxT_v1 = scipy.signal.convolve2d(
    arr, 
    dxT_oper, 
    mode='same',
    boundary='circular'
)

## BCCB tricks
dxT_oper_diag = eaglecore.utils.fourier_diagonalization(dxT_oper, arr.shape)
arr_fft_dxT_v2 = dxT_oper_diag * arr_fft
arr_dxT_v2 = numpy.real(numpy.fft.ifft2(arr_fft_dxT_v2))


## With numpy
arr_dxT_v3 = eaglecore.differential.transposed_difference_finite_circular(
    array = arr,
    axis = 1
)

print('Kernel identity :\n', kernel2d_id)
print('dxT_oper :\n', dxT_oper)

print('conv2d :\n', arr_dxT_v1)
print('BCCB :\n', arr_dxT_v2)
print('Direct :\n', arr_dxT_v3)

# print(eaglecore.differential.dxT(arr))


Kernel identity :
 [[0 0 0]
 [0 1 0]
 [0 0 0]]
dxT_oper :
 [[ 0  0  0]
 [-1  1  0]
 [ 0  0  0]]
conv2d :
 [[-1 -1 -1  3]
 [-1 -1 -1  3]
 [-1 -1 -1  3]
 [-1 -1 -1  3]]
BCCB :
 [[-1. -1. -1.  3.]
 [-1. -1. -1.  3.]
 [-1. -1. -1.  3.]
 [-1. -1. -1.  3.]]
Direct :
 [[-1 -1 -1  3]
 [-1 -1 -1  3]
 [-1 -1 -1  3]
 [-1 -1 -1  3]]


### $\nabla_{y}^{T}$

In [7]:
kernel2d_id = numpy.pad(numpy.array([[1]]), pad_width=1)

dyT_oper = eaglecore.differential.transposed_difference_finite_circular(
    array = kernel2d_id,
    axis = 0
)

## With convolution (ie spatial domain)
arr_dyT_v1 = scipy.signal.convolve2d(
    arr, 
    dyT_oper, 
    mode='same',
    boundary='circular'
)

## BCCB tricks
dyT_oper_diag = eaglecore.utils.fourier_diagonalization(dyT_oper, arr.shape)
arr_fft_dyT_v2 = dyT_oper_diag * arr_fft
arr_dyT_v2 = numpy.real(numpy.fft.ifft2(arr_fft_dyT_v2))


## With numpy
arr_dyT_v3 = eaglecore.differential.transposed_difference_finite_circular(
    array = arr,
    axis = 0
)

print('Kernel identity :\n', kernel2d_id)
print('dyT_oper :\n', dyT_oper)

print('conv2d :\n', arr_dyT_v1)
print('BCCB :\n', arr_dyT_v2)
print('Direct :\n', arr_dyT_v3)

# print(eaglecore.differential.dyT(arr))

Kernel identity :
 [[0 0 0]
 [0 1 0]
 [0 0 0]]
dyT_oper :
 [[ 0 -1  0]
 [ 0  1  0]
 [ 0  0  0]]
conv2d :
 [[-4 -4 -4 -4]
 [-4 -4 -4 -4]
 [-4 -4 -4 -4]
 [12 12 12 12]]
BCCB :
 [[-4. -4. -4. -4.]
 [-4. -4. -4. -4.]
 [-4. -4. -4. -4.]
 [12. 12. 12. 12.]]
Direct :
 [[-4 -4 -4 -4]
 [-4 -4 -4 -4]
 [-4 -4 -4 -4]
 [12 12 12 12]]
